[package]
name = "cipherpipe"
version = "0.1.0"
authors = ["nmccallu <npmccallum@redhat.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
rustls = "0.15.2"
errno = "0.2.4"
libc = "0.2.60"

[lib]
crate-type = ["cdylib"]
name = "cipherpipe"
